### ISSUE TITLE
Welcome Page

### ISSUE THREAD

**Issue by ChristopherNavo** [ChrisNavoczynski/Dog-Date#2]
## Summary
As a user, I want to add a Welcome Page that immediately welcomes the user to the app.

### Properties
- [x] Easy to view the App's title and its purpose
- [x] Easy navigate button that will lead to the signin/up screen
- [x] Font size is readable
- [x] Aesthetic meets the client's approval
- [x] Testing of new code has been added.

Welcome Screen Outcome:
![final](https://user-images.githubusercontent.com/52547964/136673556-c20f3380-99fc-439c-a255-7496fa93f0ce.PNG)

Testing Complete:
![Test](https://user-images.githubusercontent.com/52547964/136673587-6c2df131-b26a-4226-8db6-a844a4f1d681.PNG)

**Comment by ChrisNavoczynski** [comment]
Welocme/Title Screen Added
